[toolchain]
channel = "nightly"
profile = "minimal"
components = [
  "cargo",
  "clippy",
  "miri",
  "rust-analyzer",
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
targets = ["wasm32-unknown-unknown"]
